---
- name: Server infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Get VPC id
    ec2_vpc_net_facts:
      region: eu-central-1
    register: vpc
  - name: get subnet facts for VNIDEFR01-PRIV02
    ec2_vpc_subnet_facts:
      region: eu-central-1
      filters:
        "tag:Name": VNIDEFR01-PRIV02
    register: ldap_subnet
  - name: Create EC2 fro DS
    ec2:
      key_name: test
      instance_type: t2.micro
      image: ami-52ed563d
      group: ['VNIDEFR01-SGPRIV01', 'VNIDEFR01-SGPRIV02' ]
      wait: yes
      private_ip: 192.150.10.10
      exact_count: 1
      count_tag:
        role: directoryserver
      region: eu-central-1
      vpc_subnet_id: "{{ ldap_subnet.subnets[0].id }}"
      monitoring: yes
      volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 40
      instance_tags:
        role: directoryserver
  - name: get subnet facts for VNIDEFR01-PUB01
    ec2_vpc_subnet_facts:
      region: eu-central-1
      filters:
        "tag:Name": VNIDEFR01-PUB01
    register: bastion_subnet
  - name: Create Bastion
    ec2:
      key_name: test
      instance_type: t2.micro
      image: ami-c7ee5ca8
      group: VNIDEFR01-SGPUB01
      wait: yes
      exact_count: 1
      count_tag:
        role: bastion
      region: eu-central-1
      assign_public_ip: yes
      instance_profile_name: ansible
      vpc_subnet_id: "{{ bastion_subnet.subnets[0].id }}"
      monitoring: yes
      volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
      instance_tags:
        role: bastion
