---
- name: Create ECS Cluster
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get private subnets
      ec2_vpc_subnet_facts:
        region: eu-central-1
      register: subnet
    - name: Create cluster (PR for prod)
      ecs_cluster:
        name: VNIDEFR01-ECSPR01
        state: present
        region: eu-central-1
      register: ecs_cluster
    - name: Create launch configuration for nodes
      ec2_lc:
        name: VNIDEFR01-LC01
        state: present
        region: eu-central-1
        image_id: ami-40d5672f
        key_name: test
        security_groups: 'VNIDEFR01-SGPRIV01'
        instance_type: t2.micro
        instance_monitoring: True
        assign_public_ip: No
        volumes:
          - device_name: /dev/xvdcz
            volume_size: 40
            device_type: gp2
            delete_on_termination: true
      register: ec2_lc
    - name: Create autoscaling group for ECS
      ec2_asg:
        name: VNIDEFR01-ASG01
        state: present
        region: eu-central-1
        health_check_period: 60
        health_check_type: EC2
        default_cooldown: 300
        replace_all_instances: True
        launch_config_name: VNIDEFR01-LC01
        min_size: 2
        max_size: 4
        desired_capacity: 2
        vpc_zone_identifier: ["{{ subnet.subnets[1].id }}", "{{ subnet.subnets[2].id }}"]
        tags: 
          - ldap_client: True
        wait_for_instances: True
      register: ec2_asg