---
- name: Create ECS Cluster
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: get subnet facts for VNIDEFR01-PRIV01
      ec2_vpc_subnet_facts:
        region: eu-central-1
        filters:
          "tag:Name": VNIDEFR01-PRIV01
      register: priv01
    - name: get subnet facts for VNIDEFR01-PRIV02
      ec2_vpc_subnet_facts:
        region: eu-central-1
        filters:
          "tag:Name": VNIDEFR01-PRIV02
      register: priv02
    - name: Create cluster (PR for prod)
      ecs_cluster:
        name: VNIDEFR01-PRECS01
        state: present
        region: eu-central-1
      register: ecs_cluster
    - name: Create launch configuration for nodes
      ec2_lc:
        name: VNIDEFR01-LC01
        state: present
        region: eu-central-1
        image_id: ami-40d5672f
        key_name: test
        security_groups: 'VNIDEFR01-SGPRIV01'
        instance_type: r4.large
        instance_monitoring: True
        instance_profile_name: ecsInstanceRole
        assign_public_ip: No
        volumes:
          - device_name: /dev/xvdcz
            volume_size: 40
            device_type: gp2
            delete_on_termination: true
        user_data: "{{ lookup('file', 'ecs_userdata.sh') }}"
    - name: Create autoscaling group for ECS
      ec2_asg:
        name: VNIDEFR01-ASG01
        state: present
        region: eu-central-1
        health_check_period: 60
        health_check_type: EC2
        default_cooldown: 300
        replace_all_instances: True
        launch_config_name: VNIDEFR01-LC01
        min_size: 2
        max_size: 4
        desired_capacity: 2
        vpc_zone_identifier: ["{{ priv01.subnets[0].id }}", "{{ priv02.subnets[0].id }}"]
        tags: 
          - ldap_client: True
        wait_for_instances: True