---
- name: Create initial infrastructure
  connection: local
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create VPC
    ec2_vpc_net:
      name: VNIDEFR01
      cidr_block: 192.150.0.0/16
      region: eu-central-1
    register: vpc
  - name: Create IGW and attach
    ec2_vpc_igw:
      vpc_id: "{{ vpc.vpc.id }}"
      state: present
      region: eu-central-1
    register: igw
  - name: Create Public Subnet 1
    ec2_vpc_subnet:
      az: eu-central-1a
      cidr: 192.150.1.0/28
      region: eu-central-1
      vpc_id: "{{ vpc.vpc.id }}"
      resource_tags:
        Name: VNIDEFR01-PUB01
    register: pubsub1
  - name: Create Public Subnet 2
    ec2_vpc_subnet:
      az: eu-central-1b
      cidr: 192.150.2.0/28
      region: eu-central-1
      vpc_id: "{{ vpc.vpc.id }}"
      resource_tags:
        Name: VNIDEFR01-PUB02
    register: pubsub2
  - name: Create Private Subnet 1
    ec2_vpc_subnet:
      az: eu-central-1c
      cidr: 192.150.9.0/24
      region: eu-central-1
      vpc_id: "{{ vpc.vpc.id }}"
      resource_tags:
        Name: VNIDEFR01-PRIV01
    register: privsub1
  - name: Create Private Subnet 2
    ec2_vpc_subnet:
      az: eu-central-1a
      cidr: 192.150.10.0/24
      region: eu-central-1
      vpc_id: "{{ vpc.vpc.id }}"
      resource_tags:
        Name: VNIDEFR01-PRIV02
    register: privsub2
  - name: Create NAT Gateway in VNIDEFR01-PUB01
    ec2_vpc_nat_gateway:
      state: present
      subnet_id: "{{ pubsub1.subnet.id }}"
      region: eu-central-1
      wait: yes
      if_exist_do_not_create: true
    register: nat
  - name: Create route table with NAT
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc.id }}"
      region: eu-central-1
      subnets:
        - "{{ privsub1.subnet.id }}"
        - "{{ privsub2.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ nat.nat_gateway_id }}"
      tags:
        Name: VNIDEFR01-RTNAT01
      state: present
  - name: Create public route table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc.id }}"
      region: eu-central-1
      subnets:
        - "{{ pubsub1.subnet.id }}"
        - "{{ pubsub2.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id }}"
      tags:
        Name: VNIDEFR01-RTPUB01
      state: present
  - name: Create public Security group
    ec2_group:
      name: VNIDEFR01-SGPUB01
      description: Public Security group
      vpc_id: "{{ vpc.vpc.id }}"
      region: eu-central-1
      state: present
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
  - name: Create private Security group
    ec2_group:
      name: VNIDEFR01-SGPRIV01
      description: Private Security group
      region: eu-central-1
      state: present
      vpc_id: "{{ vpc.vpc.id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ pubsub1.subnet.cidr_block }}"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ pubsub2.subnet.cidr_block }}"
      rules_egress:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
  - name: Create private Security group for LDAP
    ec2_group:
      name: VNIDEFR01-SGPRIV02
      description: Private Security group for LDAP
      region: eu-central-1
      state: present
      vpc_id: "{{ vpc.vpc.id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ pubsub1.subnet.cidr_block }}"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ pubsub2.subnet.cidr_block }}"
        - proto: tcp
          from_port: 389
          to_port: 389
          cidr_ip: 192.150.0.0/16
      rules_egress:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0